### ISSUE TITLE
wa-tab-group causes a createElement error when used in a ReactJS application

### ISSUE THREAD

**Issue by fmercille** [shoelace-style/webawesome-alpha#111]
### Describe the bug
When I used a wa-tab-group (and its associated wa-tab and wa-tab-panel) components in a React app, it works fine the first time the page containing the component renders, but if I navigate away and navigate back to that page, I get a `NotSupportedError: Failed to execute 'createElement' on 'Document': The result must not have attributes`

### To Reproduce
The error can be seen in the following codesandbox: https://codesandbox.io/p/sandbox/clever-violet-mhx65w

1. Load the sandbox (wait for the preview to show)
2. Click on the "Other page" link
3. Click on the "Home" link

### Browser / OS
 - Browser: Tested on both Chrome 131 and Firefox 131

**Comment by claviska** [comment]
For troubleshooting convenience, here's the error in question.

![CleanShot 2024-12-18 at 12 35 09@2x](https://github.com/user-attachments/assets/5e74971c-24f6-4c7e-853e-fb9cd03603d1)

It appears to be coming from `react-dom`, not Web Awesome, but it could also involve some kind of conflict with the router.

I'd suggest waiting for our npm package before using Web Awesome with React. We ship React wrappers that are more idiomatic and might alleviate this problem.

I know that's probably not what you want to hear, but I'm not really sure how to troubleshoot this one further.

**Comment by fmercille** [comment]
> I know that's probably not what you want to hear, but I'm not really sure how to troubleshoot this one further.

No worries. I didn't expect an immediate fix. I'm glad to know the npm package will make things more compatible. I'm just eager to be using WA now and I'm experimenting with the alpha.

**Comment by claviska** [comment]
If you don't mind, I'm going to close this because the npm package _should_ fix this for you. If you run into any problems once it's available, let me know!
