### ISSUE TITLE
Button Groups - Drop Downs not rendering

### ISSUE THREAD

**Issue by GedMarc** [shoelace-style/webawesome-alpha#117]
### Describe the bug
Button Groups on drop downs seem to not render on the example

### To Reproduce

1. Go to 'Example Site'
2. Click on 'Button Groups'
3. Scroll down to the drop section

### Screenshots
![image](https://github.com/user-attachments/assets/e60c4344-01e3-492a-8d94-3ca32cf4ff91)

### Browser / OS
 - OS: Windows 11 2024H2
 - Browser: Edge
 - Browser version: Version 131.0.2903.99 (Official build) (64-bit)
 - Screen Reader: N/A

**Comment by GedMarc** [comment]
Split buttons also seems to be affected

**Comment by claviska** [comment]
This was fixed in the latest release, available today.
