### ISSUE TITLE
Checkbox component missing from site

### ISSUE THREAD

**Issue by GedMarc** [shoelace-style/webawesome-alpha#119]
### Describe the bug
Not sure if bug, or intentional? 
The wa-checkbox component doesn't show on the site api anymore :)
The native checkbox does, as a native input element, has the widget been swapped out for the native control?

### To Reproduce

1. Go to examples web site
2. Click on Components
3. Checkbox missing

### Screenshots
![image](https://github.com/user-attachments/assets/4c5c8551-432d-4d25-a395-e05c7abd6083)

### Additional information
All tried browsers and devices, Windows Edge/Chrome/Firefox/Opera Mac Pro Chrome/Safari

**Comment by GedMarc** [comment]
Also a possible typo? On format date? 
![image](https://github.com/user-attachments/assets/212cc4e2-afc1-4aae-8bc9-1ed51e8c2ee6)

**Comment by KonnorRogers** [comment]
> ### Describe the bug
> 
> Not sure if bug, or intentional? The wa-checkbox component doesn't show on the site api anymore :) The native checkbox does, as a native input element, has the widget been swapped out for the native control?
> ### To Reproduce
> 
> Steps to reproduce the behavior:
> 
>     1. Go to examples web site
> 
>     2. Click on Components
> 
>     3. Checkbox missing
> 
> 
> ### Demo
> ### Screenshots
> 
> ![image](https://private-user-images.githubusercontent.com/5367513/397975391-4c5c8551-432d-4d25-a395-e05c7abd6083.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NjQ4NTcsIm5iZiI6MTczNDg2NDU1NywicGF0aCI6Ii81MzY3NTEzLzM5Nzk3NTM5MS00YzVjODU1MS00MzJkLTRkMjUtYTM5NS1lMDVjN2FiZDYwODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjJUMTA0OTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODllYTU4NjExNWE1MGE5NmRlZDIwNjA4YTQ1YTM3MTA5ODkwZjJhMTM1OTdhZmIzNmQwNGJiY2E5NDgxYWNkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ol_z4Fnu0-783cBaLNJbfdhiE9M4A-qHMAb841v4drQ)
> ### Additional information
> 
> All tried browsers and devices, Windows Edge/Chrome/Firefox/Opera Mac Pro Chrome/Safari

Negative. We moved some things around and it got lost in translation. I'll work on a fix.

> Also a possible typo? On format date? ![image](https://private-user-images.githubusercontent.com/5367513/397979915-212cc4e2-afc1-4aae-8bc9-1ed51e8c2ee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NjQ4NTcsIm5iZiI6MTczNDg2NDU1NywicGF0aCI6Ii81MzY3NTEzLzM5Nzk3OTkxNS0yMTJjYzRlMi1hZmMxLTRhYWUtOGJjOS0xZWQ1MWU4YzJlZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjJUMTA0OTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU4NGExYjIxZjJkYmEwMjU5YTg4ZTg5NmI1MjBjMWQ5ODcwZDAzNWM2ZTA4ZGFjNDFkYjNjZjU5MjZjNzZjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tXJs9vqkI6O0lT7lWUjfNjRknxJumKBtU6Dy-6p3NpE)

do you mean on `<wa-format-number>`? I see it as well and will update it.

**Comment by KonnorRogers** [comment]
@GedMarc should be fixed!

**Comment by GedMarc** [comment]
![image](https://github.com/user-attachments/assets/a8767370-0d8d-4c43-a35a-8eb67930391f)

Ping :)  on the radio button for the withLabel - 

p.s. -> my understanding is usually the label is default and the icon is optional ;)
