### ISSUE TITLE
Accessibility issues with tabs

### ISSUE THREAD

**Issue by paulGeoghegan** [shoelace-style/webawesome-alpha#14]
When you first look at a tab group it notifies a screen reader user which tab is selected. however, when you select a different tab it no longer notifies you which one you have selected. Usually you can also press the tab key to enter the tab list and then use the arrow keys to navigate between the different tabs. The tabs should also have the tab role along with the other roles required.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role#example

**Comment by claviska** [comment]
What browser/screen reader combo are you using? It's announcing correctly for me in Safari + VoiceOver.

**Comment by paulGeoghegan** [comment]
@claviska I've been testing on desktop using Firefox and NVDA. It works fine with the tab components from MDN and the ones that I have personally built so I don't think that it's a browser or screen reader issue but I could be wrong.

**Comment by claviska** [comment]
@KonnorRogers can we define which browser + screen reader combos we will be officially supporting?

**Comment by KonnorRogers** [comment]
> @claviska I've been testing on desktop using Firefox and NVDA. It works fine with the tab components from MDN and the ones that I have personally built so I don't think that it's a browser or screen reader issue but I could be wrong.

Something about Firefox + VoiceOver specifically is causing this issue.
it reads as expected in Chrome / Safari + VoiceOver which makes me think it's an accessibility module issue.
<div role="tablist">
  <slot name="tab"></tab>
</div>

^ that fails

<div>
  <slot name="tab" role="tablistl></tab>
</div>

^ this works, but roles on slots can lead to other weird accessibility issues so I'll have to do some further testing.

**Comment by paulGeoghegan** [comment]
@claviska @KonnorRogers so I checked in Chrome and there is no issues. It's weird that it works fine for other tab components in Firefox though.

**Comment by KonnorRogers** [comment]
@paulGeoghegan I'm going to file a bug against Firefox about this as well, it seems like the `<slot>` is becoming part of the a11y tree.

**Comment by KonnorRogers** [comment]
@paulGeoghegan hold on a second here...I was on my personal computer just now, and its reading properly in Firefox 127.0.1

Can you check your Firefox version for me?

**Comment by KonnorRogers** [comment]
@paulGeoghegan I was just on my personal laptop using Firefox + VoiceOver and it was announcing correctly. It was not doing so in VoiceOver + Firefox on my work laptop.

I'm on Firefox 127.0.1

Do you mind checking what version of Firefox you're on and if upgrading helps? (I'm going to check my work laptop in a little bit to double check the version of Firefox there as well)

**Comment by paulGeoghegan** [comment]
@KonnorRogers  I'm on version 127.0.1 as well.

**Comment by KonnorRogers** [comment]
@paulGeoghegan Is this still an issue? I dont know if alpha v1 was the problematic one...I'm on alpha v2, and I've tested it with the following:

MacOS 14.5
Firefox 127.0.2
Safari 17.5
Chrome  126.0.6478.127

Windows 11
Firefox 127.0.2
Edge 126.0

**Comment by paulGeoghegan** [comment]
@KonnorRogers it is fixed in Chrome but not in FF. It still doesn't gain propper focus so you can't navigate with the arrow keys. All of the other issues seem to be fixed now though.

**Comment by KonnorRogers** [comment]
@paulGeoghegan Ahhhh hang on! Any chance you're usin the "Scrolling Tabs" or "Closing Tabs" examples?

IF so, in firefox overflow containers are focusable, and I _think_ thats the problem you're hitting. If you hit the "Tab" key one extra time on examples where the arrow keys dont work, does it work as expected?

**Comment by paulGeoghegan** [comment]
@KonnorRogers I'm not sure why but now it works better and no I was checking with a few different examples. Still some problems though. When pressing the up and down arrows in a horizontal list it still messes up focus in FF and there should be a way to distinguish between horizontal and vertical tab lists.

**Comment by KonnorRogers** [comment]
> @KonnorRogers I'm not sure why but now it works better and no I was checking with a few different examples. Still some problems though. When pressing the up and down arrows in a horizontal list it still messes up focus in FF and there should be a way to distinguish between horizontal and vertical tab lists.

@paulGeoghegan Seems to be another case of screenreaders ignoring an aria property. Just tested in NVDA and VoiceOver, neither one read the `aria-orientation` property 🙃 

https://codepen.io/paramagicdev/pen/abrezXg

**Comment by KonnorRogers** [comment]
There's also some relevant NVDA issues around this:

<a href="https://github.com/nvaccess/nvda/issues/6283">NVDA Issue 6283</a>

**Comment by paulGeoghegan** [comment]
@KonnorRogers sometimes I wonder what is the point of half of the aria attributes if screen readers don't even support them. I asked for an update on that NVDA issue but obviously that is nothing to do with WA.

**Comment by KonnorRogers** [comment]
@paulGeoghegan I filed a bug on VoiceOver as well.

https://feedbackassistant.apple.com/feedback/14157061
