### ISSUE TITLE
Accessibility issue with split Panel

### ISSUE THREAD

**Issue by paulGeoghegan** [shoelace-style/webawesome-alpha#21]
### Describe the bug
A bug is _a demonstrable problem_ caused by code in the library. Please provide a clear and concise description of what the bug is here.
You can't re-size the panels if you are using a screen reader.

### To Reproduce

1. Go to https://backers.webawesome.com/docs/components/split-panel
2. try to interact with the resize separator controls while using a screen reader in my case NVDA
3. Nothing happens

### Browser / OS
 - OS: Windows
 - Browser: Firefox
 - Browser version: 127.0.1
 - Screen Reader: NVDA

### Additional information
Provide any additional information about the bug here.
Honestly this isn't the biggest deal given that it's unlikely to matter to a screen reader user but it would be great even for being able to test things or if you are showing something to someone.

PS the templates definitely help.

**Comment by claviska** [comment]
I know this was filed under NVDA, but it works using Safari + VoiceOver with the `CMD` modifier and arrow keys.

@paulGeoghegan can you tell us what key's your using to resize so we can reproduce this in NVDA?

**Comment by paulGeoghegan** [comment]
@claviska ah actually I can re-size it if I hold the alt key and then use the arrows or home/end keys. It just wasn't entirely obvious how to use it but maybe that's just me. I feel like it would maybe good to add some kind of hint to let people know because I personally haven't ever had to change a value like that but again maybe it's just me.

**Comment by claviska** [comment]
No worries. I'm not as familiar with key combos in NVDA.

Side note: I noticed ARIA APG has a pattern for this now, so maybe we can align to it soon. https://www.w3.org/WAI/ARIA/apg/patterns/windowsplitter/

**Comment by paulGeoghegan** [comment]
@claviska I definitely think that would help.

**Comment by claviska** [comment]
It looks like we already align with the keyboard shortcuts [mentioned here]() except for this one:

- <kbd>Enter</kbd>: If the primary pane is not collapsed, collapses the pane. If the pane is collapsed, restores the splitter to its previous position.

I've [added this to Shoelace](https://github.com/shoelace-style/shoelace/pull/2234) and Web Awesome. It will be available in the next release of both libraries.
