### ISSUE TITLE
Accessibility issue with Relative Time

### ISSUE THREAD

**Issue by paulGeoghegan** [shoelace-style/webawesome-alpha#22]
### Describe the bug
A bug is _a demonstrable problem_ caused by code in the library. Please provide a clear and concise description of what the bug is here.
Screen readers always read the full date, time, timezone, and time difference.

### To Reproduce

1. Go to https://backers.webawesome.com/docs/components/relative-time
2. Navigate to one of the relative time components while using a screen reader
3. The full date is read e.g. The 15th of July 2020 at 2:17pm gmt+1 4 years ago instead of just saying 4 years ago.

      ### Browser / OS
       - OS: Windows
       - Browser: Firefox
       - Browser version: 127.0.1
       - Screen Reader: NVDA

**Comment by claviska** [comment]
Thanks for reporting this! I've fixed the problem with relative time in screen readers and it will be available in Web Awesome 1.0.0-alpha.2.
