### ISSUE TITLE
wa-icon sets to filled even when using outline (Tabler)

### ISSUE THREAD

**Issue by 100020001** [shoelace-style/webawesome-alpha#4]
> 
> TABLER ICONS:
> 
> <script type="module">
>   import { registerIconLibrary } from '/dist/webawesome.js';
> 
>   registerIconLibrary('tabler', {
>     resolver: name => `https://cdn.jsdelivr.net/npm/@tabler/icons@1.68.0/icons/${name}.svg`
>   });
> </script>

Icons are filled.
variant=outline didn't solve it.

Using this for now..

```
wa-icon {
    &::part(svg) {
        fill: none;
    }
}
```

**Comment by claviska** [comment]
Thanks for catching this! I've updated the docs with a mutator that removes the fill.
