### ISSUE TITLE
wa-checkbox submitting on instead of assigned value when toggled

### ISSUE THREAD

**Issue by bitbandit01** [shoelace-style/webawesome-alpha#59]
### Describe the bug
Using the wa-checkbox component with a name value pair.  The value is not maintained within the component when it is toggled. If the checkbox is toggled off and on again, the value submitted with the form will be "on" instead of the assigned value.

### To Reproduce

[Link to codepen](https://codepen.io/bitbandit01/pen/wvLWXYR)

Results can be viewed in console.  
Click the submit button on load and you will get expected behaviour
`FormData { test → "myvalue" } `

Then uncheck the box and you also get expected behaviour
`FormData(0)`

Then recheck the box and you get incorrect behaviour (should be "myValue")
`FormData { test → "on" }`

### Browser / OS
 - OS: Fedora 40
 - Browser: Firefox
 - Browser version: 128.0

```[tasklist]
### Tasks
```

**Comment by KonnorRogers** [comment]
Thanks! Let me take a look, I _think_ I have this fixed in an SSR branch I'm working on , but I'll add a regression test for this.

**Comment by KonnorRogers** [comment]
Confirmed, will be fixed in the next release! (regression test added)
