### ISSUE TITLE
Icon button tooltip documentation error (minor)

### ISSUE THREAD

**Issue by aaronpinero** [shoelace-style/webawesome-alpha#6]
https://backers.webawesome.com/docs/components/icon-button#icon-button-with-tooltip
In the documentation for a tooltip on an icon button, the text instructs the user to wrap the button with a tooltip component. However, the code (and apparently correct implementation) is to create a wa-tooltip element with a for attribute that references the id attribute of the icon button.

**Comment by lindsaym-fa** [comment]
Good catch, @aaronpinero! We recently updated tooltips to reference an `id`, and we missed this part of the docs. We'll get it fixed!
