### ISSUE TITLE
Carousel pagination markers do not change when items are swiped on mobile

### ISSUE THREAD

**Issue by gjrogala** [shoelace-style/webawesome-alpha#65]
Describe the bug

When viewed on a mobile device (only tested iPhones) the pagination markers below the slider do not change accordingly when carousel items are swiped.   

To Reproduce

1. Go to Carousel documentation page on WebAwesome Alpha
2. Click on 'Edit' for any Carousel example that has pagination and mouse dragging enables and open the Codepen page on mobile
3. Swipe the items 

Demo

Here is my demo (open on mobile)
https://codepen.io/grzegorz-rogala/pen/LYKxOZR/0b4177bc561512ddcf1bb9dda38d8e60

### Browser / OS
 - OS: Mac
 - Browser: Mobile Safari, Mobile Chrome and Mobile Firefox
 - Browser version: 17.6 same as the iOS

**Comment by claviska** [comment]
I reduced this and it looks like it's behaving correctly.

https://codepen.io/claviska/pen/poMaZXL?editors=1100

Note that the following attributes are set, which I think it causing confusion:

```html
<wa-carousel ... slides-per-page="3" slides-per-move="3">
```

Slides per page will _show_ three per "slide" and slides per move determines how many slides the carousel moves with previous/next. In its current state, you need to drag three slides for the dot to change. However, if you set `slides-per-move` to `1` you'll notice it update even when you slide just one.

If I'm missing something, please let me know and I'll reopen for further investigation.

**Comment by claviska** [comment]
> when I swipe my finger across the slides from left to right (as mouse dragging is enabled

Ah, this is what confused me. _Mouse dragging_ is actually handled in a separate code path because touch "just works" due to the use of scroll snap. It looks like that is working fine.

However, _swiping_ no longer causes the navigation dots to update.

Thanks for clarifying!

**Comment by claviska** [comment]
This has been fixed in Web Awesome alpha.5.

Updated example: https://codepen.io/claviska/pen/zxOZzqJ?editors=1100
