### ISSUE TITLE
Radio Button initial checked state not consistently applied

### ISSUE THREAD

**Issue by sswinford-dcc** [shoelace-style/webawesome-alpha#71]
### Describe the bug
Radio Buttons are not consistently receiving the "checked" attribute on render when the value of the Radio Button is the same as the value for the Radio Group.

### To Reproduce

1. Add code block for radio group with radio buttons.
2. Add a "value" to the radio group that corresponds with a button's "value".
3. Load the page with the radio group component.

### Demo
https://codepen.io/StephanJS/pen/yLdqwKE

### Screenshots
![bug-radiobutton-codepen](https://github.com/user-attachments/assets/4fe72e02-3706-420a-8066-70d099c28ea7)

### Browser / OS
 - OS: Windows 11
 - Browser: Edge
 - Browser version: 128.0.2739.42
 - Screen Reader: N/A

### Additional information
Radio Buttons consistently load correctly on the WA documentation page, however on CodePen or my own webpages it very rarely works correctly. It seems to work initially, but then it will stop working consistently (maybe 1 in 20 times it will load correctly).

Regular radios do not seem to be affected by this bug and work as expected.

**Comment by claviska** [comment]
Hi there. I don't think we're going to spend time on this component because we're deprecating it. Instead, the radio item component is getting updated to support custom styles which will cover this use case.

We're hoping to have that change out soon! Thanks for your patience.
