### ISSUE TITLE
'@shoelace-style/localize' in alpha.3

### ISSUE THREAD

**Issue by AndreasRavn** [shoelace-style/webawesome-alpha#81]
### Describe the bug
Updated alpha.2 to alpha.3 and webawesome fails with a typeerror:

"TypeError: Module name, '@shoelace-style/localize' does not resolve to a valid URL."

### To Reproduce
Use the standard CDN autoloader from the installation page.

### Demo

```
<!DOCTYPE html>
<html>

    <head>
        <title>Bug</title>

        <link rel="stylesheet" href="https://early.webawesome.com/webawesome@3.0.0-alpha.3/dist/themes/default.css" />
        <script type="module" src="https://early.webawesome.com/webawesome@3.0.0-alpha.3/dist/webawesome.loader.js" ></script>
    </head>

    <body>
        Hello world
    </body>

</html>
```

### Screenshots
<img width="644" alt="Skærmbillede 2024-09-24 kl  14 21 51" src="https://github.com/user-attachments/assets/5f949dc7-359d-4514-90c9-b069146a3b09">

### Browser / OS
 - OS: MacOS 15.0
 - Browser: Safari, Edge, Chrome
 - Browser version: latest stable of all 3 browsers tested
 - Screen Reader: N/A

**Comment by claviska** [comment]
Sorry about that! In this release, we added a new dist to support SSR and npm users and the wrong folder was being copied to the CDN. I've released 3.0.0-alpha.4 which corrects this, and I've verified that it works correctly.

Thanks for reporting this to us!
