### ISSUE TITLE
Select initial value

### ISSUE THREAD

**Issue by AndreasRavn** [shoelace-style/webawesome-alpha#82]
### Describe the bug
In alpha.4 setting value on the wa-select doesn't seem to set initial value.

### To Reproduce
```
<wa-select value="option-1 option-2" multiple clearable>
  <wa-option value="option-1">Option 1</wa-option>
  <wa-option value="option-2">Option 2</wa-option>
  <wa-option value="option-3">Option 3</wa-option>
  <wa-option value="option-4">Option 4</wa-option>
</wa-select>
```

### Demo

https://backers.webawesome.com/docs/components/select#setting-initial-values
Example on documentation page works (maybe because its SSR?), but the editable example on codepen doesn't.

### Screenshots
<img width="903" alt="Skærmbillede 2024-09-24 kl  16 29 28" src="https://github.com/user-attachments/assets/5cd5d4f3-307b-4065-a6b6-7afedf7c1de3">

### Browser / OS
 - OS: MacOS 15.0
 - Browser: Chrome, Edge, Safari
 - Browser version: Latest stable

**Comment by KonnorRogers** [comment]
Thanks for the report, let me take a look and see whats up.

**Comment by HovKlan-DH** [comment]
When this is even affecting the examples in the documentation, then I am wondering why this has not been caught in the testing process? 🤔

**Comment by KonnorRogers** [comment]
> When this is even affecting the examples in the documentation, then I am wondering why this has not been caught in the testing process? 🤔

im not sure i follow. This issue is a race condition that is largely dependent on timing of connection of elements and a few other factors, so its pretty challenging to reproduce.

The examples worked fine on the actual documentation page.

As for the bug itself, I fixed it, added regression tests, and backported the fix to Shoelace, and it should be part of the next alpha release.

**Comment by HovKlan-DH** [comment]
Sorry, I was not at all my intention to come with a harsh comment, though I can understand now, that I probably could have asked this a little better. I was just thinking that the current demo-code could easily be tested between releases, but I fully understand that there can be relevant timing issues, which I did not consider.

Thanks a lot for your great work with Web Awesome 😊

**Comment by KonnorRogers** [comment]
> Sorry, I was not at all my intention to come with a harsh comment, though I can understand now, that I probably could have asked this a little better. I was just thinking that the current demo-code could easily be tested between releases, but I fully understand that there can be relevant timing issues, which I did not consider.
> 
> Thanks a lot for your great work with Web Awesome 😊

All good.

FWIW, this has been a long standing issue with this component that I was never quite able to fully wrangle until recently. If you're curious about the fix, the PR for Shoelace is here:

https://github.com/shoelace-style/shoelace/pull/2204

and is roughly the same thing I did to fix it in web awesome.

**Comment by ziofat** [comment]
I don't think it is really related to lazy laoding options. I can easily reproduce this issue from the codepen provided by docs page which has no lazy loading options.
The initial render is OK, but after changing the value in HTML(which cause a refresh), the pre-selected options are gone.
![image](https://github.com/user-attachments/assets/b4a41901-4ef8-474c-a4fb-2a6b7c172795)

**Comment by KonnorRogers** [comment]
Thats most 

> I don't think it is really related to lazy laoding options. I can easily reproduce this issue from the codepen provided by docs page which has no lazy loading options. The initial render is OK, but after changing the value in HTML(which cause a refresh), the pre-selected options are gone. ![image](https://private-user-images.githubusercontent.com/8521174/380357226-b4a41901-4ef8-474c-a4fb-2a6b7c172795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTQ3OTAsIm5iZiI6MTcyOTkxNDQ5MCwicGF0aCI6Ii84NTIxMTc0LzM4MDM1NzIyNi1iNGE0MTkwMS00ZWY4LTQ3NGMtYTRmYi0yYTZiN2MxNzI3OTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjZUMDM0ODEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU4NzA2ZDEyYTI1NTRiYTlmMjEyOTg1M2QyOGEwY2VmMDdkNWFjODc5NjIyZDNiZmVhNDkyYjQ1YmMwZTU2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CNVAobWCo7EhIhv93-YjF_AktViB9EIYkxByXAGbwx0)

I'm pretty positive the problem is a load order issue. Its not technically lazy loading thats the problem, just usually when it shows up due to timings.

Its what happens when the `<wa-select>` registers before the `<wa-option>`. This should be solved with the next release. I'll ping here and see if you can still reproduce after the next release.

**Comment by KonnorRogers** [comment]
@ziofat Better yet, let me know if this one works for you.

https://codepen.io/paramagicdev/pen/abeEmZO?editors=1000

This forces the `<wa-option>` to register before `<wa-select>` and seems to behave as expected for me.

**Comment by ziofat** [comment]
@KonnorRogers It works!
