### ISSUE TITLE
checked wa-checkbox causes layout shift

### ISSUE THREAD

**Issue by timsnadden** [shoelace-style/webawesome-alpha#86]
### Describe the bug
Checking a checkbox can alter the layout causing the checkbox and label text to shift

### To Reproduce

1. Go to https://backers.webawesome.com/docs/components/checkbox
2. Check the example checkbox
3. Note the layout shift (text and checkbox moving down)

### Screenshots

https://github.com/user-attachments/assets/2f085a0e-ed7c-42b8-9b8e-00221463af90

### Browser / OS
 - OS: Mac
 - Browser: Chrome, Firefox, Safari, Edge
 - Browser version: latest

### Additional information
Setting `overflow: hidden` on the `<wa-checkbox>` prevents this layout shift. This is likely not the fix but could be a clue as to what is required to fix this

**Comment by claviska** [comment]
Thanks for reporting this. A fix has landed and will be available in the next alpha release.
