### ISSUE TITLE
Textarea with pre-filled text cannot delete all text

### ISSUE THREAD

**Issue by HovKlan-DH** [shoelace-style/webawesome-alpha#90]
### Describe the bug
When purely deleting all the pre-filled text in a textarea, then as soon as the textarea looses focus, then the original text reappears.

### To Reproduce

1. Go to [https://jsfiddle.net/scaky7bd/](https://jsfiddle.net/scaky7bd/)
2. Click in the textarea field
3. Mark all text and delete it; "Test 1 2 3"
4. Point and click your mouse outside the textarea
5. See error - the text "Test 1 2 3" will reappear

### Demo

https://jsfiddle.net/scaky7bd/

### Browser / OS
 - OS: Windows
 - Browser: Chrome
 - Browser version: 130.0.6723

### Additional information
When editing the text (removing some characters or adding some new chars), then it will correctly keep that specific text - only when deleting everything, it seems to be a problem.

**Comment by HovKlan-DH** [comment]
Any news on this one? It is quite a surprise when you discover much later that your stuff does not get deleted 😁

**Comment by KonnorRogers** [comment]
Yup! Will be fixed in the next release!

**Comment by claviska** [comment]
I'm happy to report this has been fixed and is available in today's release.
