### ISSUE TITLE
Opening a dialog using `show()` closes it immediately

### ISSUE THREAD

**Issue by julianrubisch** [shoelace-style/webawesome-alpha#95]
### Describe the bug
Opening a dialog using `show()` results in weird behavior:

### To Reproduce

1. Go to https://backers.webawesome.com/docs/components/dialog
2. Open the browser devtools and store any `wa-dialog` element as a global variable
3. Call `show` on it
4. It gets closed immediately 

### Screenshots

https://github.com/user-attachments/assets/14c82591-f90e-42ba-8954-0fa09e9081ee

### Browser / OS
 - OS: Mac OS 14.7 Sonoma
 - Browser: Brave
 - Browser version: 1.7.123 (Chromium 130, arm64)

**Comment by KonnorRogers** [comment]
🤔 odd. I'll take a look. This *may* have to do with us SSRing these components. We recently tracked down a bug around animations. @claviska I'll take a look at this once you get the decorator changes merged.
